### ISSUE TITLE
Inconsisten "usage" documentation for "--trees" and/or "--to"

### ISSUE THREAD

**Issue by behoffski** [luarocks/luarocks-site#100]
The synopsis for LuaRocks 2.4.1 includes the line:
	/usr/local/bin/luarocks [--from=<server> | --only-from=<server>] [--to=<tree>] [VAR=VALUE]... <command> [<argument>] 

However, the GENERAL OPTIONS list includes the following:
	--tree=<tree>          Which tree to operate on.

So, is "--to" the general option, or is "--tree"?  Or is there some other configuration/combination in action, perhaps on a command-by-command basis?

**Comment by leafo** [comment]
This is the issues tracker for the website, did you mean to post here? https://github.com/luarocks/luarocks/issues

**Comment by hishamhm** [comment]
@behoffski `--to` is an old synonym to `--tree`. In any case, the references to `--to` and friends were removed in the dev branch, thanks.
