### ISSUE TITLE
Fatal error C1083: Cannot open include file '(filename)': No such file or directory

### ISSUE THREAD

**Issue by TheElementalOfCreation** [luarocks/luarocks-site#101]
I keep getting this error on everything I try to install with luarocks, and it is also a different file. For BigInt it was string.h. For luafilesystem is was errno.h. For lbc it was ctype.h. Is there something wrong with these rocks, am I doing something wrong, what? I am on windows, if that means anything.

**Comment by leafo** [comment]
This issues tracker is for the luarocks.org website, if you have issues with the command line tool you can post here: https://github.com/luarocks/luarocks/issues
