### ISSUE TITLE
Suggestion: Ability to add rockspecs for distributions to bypass installation/compilation.

### ISSUE THREAD

**Issue by thornley-touchstar** [luarocks/luarocks-site#103]
I want to throw an idea past the maintainers of luarocks. 

I have been experimenting with luarocks and the openwrt/lede distribution. These embedded devices don't typically self-contain development/compilation environments and run arbitrary architectures, so compiling on the hardware is usually out of the question. Now the distribution comes with its own package management system (opkg) and I was thinking it might make sense to try and bridge the gap between the build root packaging system and luarocks.

Currently openwrt/lede has a bunch of lua packages like luasocket, dkjson, lua-rs232, etc these are installed in the LUA_PATH under /usr/lib/lua with no rockspecs so while the dependencies can exist for many lua rocks, they are not manifested, and hence not available or met. 

I'm looking for suggestions but I was thinking of a means to use luarocks during opkg installation (if present) to install the rockspec correctly (just the manifest + rockspec structure in /usr/lib/luarocks/rocks) without actually installing or moving anything around. 

Obviously any hints on how to go about this would be great, I'm very much interested in contributing! 

:)

**Comment by leafo** [comment]
Hey, this is the issues tracker for the website of luarocks. You'll probably want to post here instead: https://github.com/luarocks/luarocks/issues

BTW, you might want to look into the `rocks_provided` configuration option, it lets you say which modules are already installed in the system, and luarocks will not try to install them.

**Comment by thornley-touchstar** [comment]
@leafo Got it, rocks_provided sounds exactly like what I am after. Sorry for polluting the wrong repository! ;)
