### ISSUE TITLE
Broken password reset functionality

### ISSUE THREAD

**Issue by last-khajiit** [luarocks/luarocks-site#104]
I tried to reset password for my account on Luarocks.org two days. When I submit form with email I get message that mail with reset information was sent to my email, but I didn't receive it (yes, I checked spam folder). Can you check it, please?

**Comment by leafo** [comment]
Sorry about the delay. It should be fixed now, try it again. Our mail provider changed some rules about outgoing mail that caused emails to get blocked. I changed the domain the mail is sent from

**Comment by last-khajiit** [comment]
Thanks for your help! 
I'll check it and 'll try to reset my pass a bit later

**Comment by last-khajiit** [comment]
Hi, I just tried to reset my pass and I successfully did it!
All works nice, thanks!

**Comment by ChillerDragon** [comment]
Just FYI my reset email ended up in the gmail spam folder. I clicked "No spam" hope it helps.
