### ISSUE TITLE
rerooting package

### ISSUE THREAD

**Issue by msva** [luarocks/luarocks-site#107]
Hi there!
Is it a description of package rerooting procedure somewhere?

I'm the new upstream for `htmlparser` rock, but it is already loaded by `luarocks` user and added to root manifest (so, users complaining they can't "easily" install proper version).

**Comment by leafo** [comment]
Hey, sorry about the delay, I missed this ticket. There aren't any directions on the site yet, but there should be. 

We have an automated system that allows owners of github repositories to take over the package on luarocks.org. It doesn't look like you are the owner in the rockspec though. If we can get confirmation from @wscherphof I can make you the owner.

Thanks

**Comment by msva** [comment]
@leafo He's rerooted repo to me.
I agree to wait for his "direct" confirmation, but, just curious, doesn't github's redirect from https://github.com/wscherphof/lua-htmlparser to https://github.com/msva/lua-htmlparser (check it yourself with curl :D) enough confirmation? :)

// Btw, it looks like @wscherphof is either too busy or AFK to vacation if he didn't show here for 3 days :)

**Comment by msva** [comment]
Looks like @wscherphof can't personally confirm the package transition here, while, as I said above, that fact can be checked by opening "old" address and looking where it redirects https://github.com/wscherphof/lua-htmlparser (even current luarocks users installs packages from my repo, but they can't gen updates without luarocks magic) 😢

**Comment by wscherphof** [comment]
Sorry to have overlooked this :-(

msva may own htmlparser :-)

Cheers, Wouter


Op do 1 jun. 2017 om 09:18 schreef Vadim A. Misbakh-Soloviov <
notifications@github.com>:

**Comment by msva** [comment]
@wscherphof thanks a lot :)

@leafo ping? 😸

**Comment by leafo** [comment]
Sorry about the delay, @msva I notice that your copy of the module doesn't have all versions. Could you bring the older versions over in case anyone is depending on them.

Thanks

**Comment by msva** [comment]
@leafo done. I added all of the versions in both luarocks and in the repo (tags and in-repo rocks)

**Comment by leafo** [comment]
Thanks, it's now there: https://luarocks.org/search?q=htmlparser
