### ISSUE TITLE
Use GitHub email api to get email address of user

### ISSUE THREAD

**Issue by leafo** [luarocks/luarocks-site#115]
`user.email` is only available if the account has a publicly listed email address. You'll need to use the emails api endpoint to fetch the email address: https://developer.github.com/v3/users/emails/

I added a temporary message but we should fetch their email so anyone can log in: https://github.com/luarocks/luarocks-site/blob/2ad70c3e59dceaa61225f875e1e74579f4a1ef07/applications/github.moon#L73

**Comment by aajjbb** [comment]
somehow the commit that address this issue is in the #114. I don't know how this happened.

**Comment by leafo** [comment]
@aajjbb do you want to pull it out into seprate pull request?

**Comment by aajjbb** [comment]
This seems much wiser.

**Comment by aajjbb** [comment]
Closed via #116
