### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by OmnissiahZelos** [luarocks/luarocks-site#132]
I am trying to install it on a windows 7 computer and all I get is "Cannot find the path" error whenever I try to install it.

**Comment by leafo** [comment]
Hello, this is the issues tracker for the luarocks website. Are you sure you aren't looking for the luarocks repository? https://github.com/luarocks/luarocks

**Comment by chandraadhikari** [comment]
I get this error when running: luarocks search luasocket or json4lua
Warning: Failed searching manifest: Failed loading manifest: Failed fetching manifest for http://luarocks.org/repositories/rocks

Error: No results matching query were found.

**Comment by leafo** [comment]
@chandraadhikari this is the wrong repository. This repository is for the luarocks website, not the command line tool. Try https://github.com/luarocks/luarocks/issues
