### ISSUE TITLE
abandoned module "lua-resty-jwt"

### ISSUE THREAD

**Issue by cdbattags** [luarocks/luarocks-site#133]
Hi folks, so we have a discussion going on over at https://github.com/SkyLothar/lua-resty-jwt/pull/79 and since this module looks to be abandoned we're looking to transfer ownership. How would we go about this? I'm looking to upload a new version by end of day today.

See my fork at https://github.com/cdbattags/lua-resty-jwt. What would this process look like?

**Comment by leafo** [comment]
We don't transfer ownership, instead we can change which module with that name gets placed in the root manifest. I can replace a module owned by you with the one currently on the root manifest.

Make sure you have all the same versions that are on the existing version available for download to ensure no one's builds break. Link me luarocks.org links to your module and the one you want it to replace.

Tagging @SkyLothar in case they respond.

**Comment by cdbattags** [comment]
All versions minus the odd `-0` and `-1` that I can't find tags for in his previous source are accounted for.

Please replace https://luarocks.org/modules/skylothar/lua-resty-jwt with https://luarocks.org/modules/cdbattags/lua-resty-jwt if all things look good on your end!

You'll see I added a v0.1.12 for the new changes.

**Comment by cdbattags** [comment]
Builds are passing as found at https://travis-ci.org/cdbattags/lua-resty-jwt with the help of @euank and @cybrq-as!

**Comment by cdbattags** [comment]
Looks like "lua-resty-hmac" also needs to be transferred to @jkeys089!

**Comment by cdbattags** [comment]
Any update on this today?

**Comment by cdbattags** [comment]
Thanks! I see that mine has now replaced in root manifest!
