### ISSUE TITLE
Change email?

### ISSUE THREAD

**Issue by telemachus** [luarocks/luarocks-site#155]
Hi,

I created an account with an email address, but now I'm giving up that email. Is there a way to change my email for login (and other) purposes? (I can't see a way to do this in my settings on the site.)

Thanks, Peter

**Comment by leafo** [comment]
Can you email me leafot@gmail.com using the email address that currently owns the account and tell me what email address to update the account to. I can make the change for you.

Thanks

**Comment by telemachus** [comment]
@leafo I've written twice in the last two weeks, but I haven't heard anything. If you didn't get the emails, please check your spam folder. If you need me to mail again—or try something else—please let me know. I hope to have this settled before I lose that email. Thanks.

**Comment by leafo** [comment]
Sorry about that. The email address is now updated.

**Comment by telemachus** [comment]
Thanks so much.
