### ISSUE TITLE
Search suggestion: how to store files

### ISSUE THREAD

**Issue by vadi2** [luarocks/luarocks-site#158]
Please mention the best practice on how to store files using Lapis. It seems that for small files, base64 is okay, while disk should be used for bigger files.

**Comment by leafo** [comment]
Um, not sure this is the right kind of issue for this. This is for suggestions where the search on luarocks.org wasn't working as expected.

For all my projects, I tend to use cloud storage instead of putting things directly into the database or trying to manage them on disk.

**Comment by vadi2** [comment]
Oops, you're right, I didn't notice. The link on https://leafo.net/lapis/reference.html takes you here.

**Comment by leafo** [comment]
Thanks, spotted the issue
