### ISSUE TITLE
module 'batcher' not found:No LuaRocks module found for batcher

### ISSUE THREAD

**Issue by song984888** [luarocks/luarocks-site#159]
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:383: module 'batcher' not found:No LuaRocks module found for batcher
	no field package.preload['batcher']
	no file '/root/.luarocks/share/lua/5.1/batcher.lua'
	no file '/root/.luarocks/share/lua/5.1/batcher/init.lua'
	no file '/root/torch/install/share/lua/5.1/batcher.lua'
	no file '/root/torch/install/share/lua/5.1/batcher/init.lua'
	no file './batcher.lua'
	no file '/root/torch/install/share/luajit-2.1.0-beta1/batcher.lua'
	no file '/usr/local/share/lua/5.1/batcher.lua'
	no file '/usr/local/share/lua/5.1/batcher/init.lua'
	no file '/root/.luarocks/lib/lua/5.1/batcher.so'
	no file '/root/torch/install/lib/lua/5.1/batcher.so'
	no file '/root/torch/install/lib/batcher.so'
	no file './batcher.so'
	no file '/usr/local/lib/lua/5.1/batcher.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
	/root/Basset/src/basset_train.lua:5: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by hishamhm** [comment]
@song984888 this repository is for the luarocks.org website, not the LuaRocks tool or packages. You might want to check the Torch Github repo instead!
