### ISSUE TITLE
Luarocks timeouts pulling packages?

### ISSUE THREAD

**Issue by jeremyjpj0916** [luarocks/luarocks-site#174]
Having some of my pipeline builds failing recently trying to pull down my luarocks packages:

![image](https://user-images.githubusercontent.com/31913027/114511734-4c5f8f80-9c06-11eb-9278-b7812bab1ce6.png)

Was testing via curl just doing ```curl -k https://luarocks.org/kong-splunk-log-0.3-3.src.rock -vv``` , it succeeded about 2 times then failed the 3rd time with a hanging timeout. Server stressed atm? 

```
➜  ~ curl -k https://luarocks.org/kong-splunk-log-0.3-3.src.rock -vv
*   Trying 45.33.61.132...
* TCP_NODELAY set
* Connected to luarocks.org (45.33.61.132) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=luarocks.org
*  start date: Mar 21 23:11:37 2021 GMT
*  expire date: Jun 19 23:11:37 2021 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /kong-splunk-log-0.3-3.src.rock HTTP/1.1
> Host: luarocks.org
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 504 Gateway Time-out
< Server: nginx/1.18.0
< Date: Tue, 13 Apr 2021 07:09:49 GMT
< Content-Type: text/html
< Content-Length: 167
< Connection: keep-alive
<
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
* Connection #0 to host luarocks.org left intact
* Closing connection 0
```

Usually luarocks org has been stable like a tank. This is new to me.

**Comment by jeremyjpj0916** [comment]
Wasn't sure if this was the site or https://github.com/luarocks/luarocks/issues/1299 more appropriate. Feel free to close the one where it does not belong.

**Comment by hishamhm** [comment]
Yes, looking at the logs it seems the server has been stressed intermittently, I'm looking at what's going on!

**Comment by jeremyjpj0916** [comment]
@hishamhm Appreciate it! Let me know when you want me to re-test.

**Comment by leafo** [comment]
There were a few db errors from connection limits and I updated the postgres config to work around that, but that doesn't appear to be related to the issue as it would not cause timeouts. It looks like it's timing out while trying to hit the upstream for the rock/rockspec files (which is google cloud storage in our case). Still taking a look

**Comment by leafo** [comment]
Give it another shot, I've updated the configuration about how we proxy to the storage files, I'm not seeing any timeouts now

**Comment by jeremyjpj0916** [comment]
Giving it a test, will report back

**Comment by jeremyjpj0916** [comment]
Working good now! Closing issue, thanks for quickly addressing it.
