### ISSUE TITLE
Front page has version 3.7.0 in Quick Start example, should be 3.8.0

### ISSUE THREAD

**Issue by behoffski** [luarocks/luarocks-site#179]
The front page of https://luarocks.org/ has a "get started" link near the top,
leading to: https://luarocks.org/#quick-start , with instructions for a GNU/Linux
system.

The first three lines of the example use 3.7.0 as the tarball version.  This
is no longer the latest release, which is 3.8.0.  (I assume 3.8.0 is "stable".)

Existing example code under Quick Start:
 
        $ wget https://luarocks.org/releases/luarocks-3.7.0.tar.gz
        $ tar zxpf luarocks-3.7.0.tar.gz
        $ cd luarocks-3.7.0

**Comment by hishamhm** [comment]
Fixed, thank you! The repo was up-to-date but the front page had not been pushed.
