### ISSUE TITLE
/usr/bin/bash: c:lualuarocks-3.8.0node_modules.bintsc.cmd: command not found

### ISSUE THREAD

**Issue by ispeedyg** [luarocks/luarocks-site#185]
Bare with me. I am going to try to explain. I am new to coding. Wanting to learn LUA because it happens to be the language GrandMA lighting consoles allow to manipulate the code. I ran into your site said this looks great but had been screwing around intalling uninstalling this that and the other. I think the one that nailed me was trying the react create one and putting my folder that i installed LUA 5.4 on with binaries in the middle of and well you can imagine. I have jumped back to a version of my computer before i got into this so an image from around march 2022. And have been on a trek to install luarocks. I have tried 2016.9.30, 3.9.0, 3.8.0 is where i am at now. It has been a long journey with this makefile stuff. I am so close to getting the package built but I cannot get the very beginning to go. As you can see in the screen shots. Even my greenhorn ass can understand why bintsc.cmd command not found wont work. I have dug and dug. I have npm uninstall -g typescript, choco install typescript, yarn this and plain run .exe installs. I have went digging the black hole of where to find the exact script that writes that line. I have spent the last few days just trying to install one of these lua rocks builds. I have copied and pasted a bunch of different task.json scripts which from what I understand gets called right away and it immediately sends for the init command to make the  tsjconfig so it can then move to the launch.json. i even tried taking the tsconfig created in a blank folder the one in the screen shot with all the commented out stuff that i just installed and pasted it into the .vscode folder and i know it is because of that misspell in the beginnning that is why i cannot get moved on.  plus i am not very good yet but how do i pick the correct launch debugger? that will be the next hurdle. i am at a stuck and frustrated point. if someone can give me a few pointers to get this built and done so i can install it and move on learning how to make scripts i would really appreciate it. Thanks in advance. 
![tsconfig_err](https://user-images.githubusercontent.com/12056754/176598776-bc7fc718-21ec-4dca-9002-e5364975a3fb.png)
<img width="665" alt="tsconfig_err2" src="https://user-images.githubusercontent.com/12056754/176598778-12ba015e-594a-4fd7-a919-2201899bc182.png">

**Comment by hishamhm** [comment]
@ispeedyg Hi! 

(First, this is the repository for the LuaRocks website (web pages and stuff), not the tool itself.)

I'm confused as to why you are trying to build LuaRocks using TypeScript tools. It has nothing to do with `node`, `tsc` or the like; it's a pure Lua tool.

To use LuaRocks on Windows, just download the all-in-one executable `luarocks.exe` from here: https://github.com/luarocks/luarocks/wiki/Download — to effectively use Lua extensions, you'll most likely need a C compiler such as mingw or Microsoft Visual Studio and configure LuaRocks to find them using `luarocks config`.

But if what you want to use Lua for is with an embedded tool such as grandMA, you should instead write plugins for that directly and run using the tools provided by that product; you most likely don't need LuaRocks or a separate Lua installation for that.

**Comment by ispeedyg** [comment]
Thanks for the information. I am new to this. I wanted to install the one that has the create recreate package with it. As a whole. There is no embedded tool for GrandMA yet who knows maybe I will create one grandmarocks.roc LOL As far as my problem earlier with the . in the wrong place I am starting to narrow it down in the lisass lib where there is a / and i believe it needs to be a \. But I have not verified it yet. But at least it has been a learning process. If i just install the binaries to a folder and place a luarocks folder in there and say have my MA folder in the folder as well. Also adding the folder to the :PATH will both be able to pull from the 1 or will I need to place the binaries in the folders separately?  Oh and were is the correct place to place a request for help? Thanks Speedy
