### ISSUE TITLE
Error while uploading a module

### ISSUE THREAD

**Issue by AadiS11** [luarocks/luarocks-site#187]
I am trying a upload a module to luarocks but when I run the `luarocks upload` command, I get the following error: <br/>
`Cloning into 'kong-audit-log'...`<br/>
`fatal: unable to connect to github.com:`<br/>
`github.com[0: 13.234.176.102]: errno=Resource temporarily unavailable`<br/>

The source url in the rockspec file is this: `git://github.com/mykaarma/kong-audit-log`<br/>

When I change the source url to `https://github.com/mykaarma/kong-audit-log`, the module gets uploaded successfully but then it gives the following error during installation: <br/>
`Error: Couldn't extract archive /tmp/luarocks_audit-log-0.1.0-1-5270308/kong-audit-log: unrecognized filename extension`

**Comment by hishamhm** [comment]
@AadiS11 You need to upgrade to the latest luarocks CLI tool (or at least 3.8.0) in order to use `git://github.com` URLs.

Alternatively, you can change the URL to `git+https://github.com`
