### ISSUE TITLE
All lua cmsgpack rockspec files need git:// changed to https://

### ISSUE THREAD

**Issue by EncryptShawn** [luarocks/luarocks-site#191]
Super quick and simple change on your site that would fix a lot of deployments for a lot of people.

These hosted URL's need to be updated
https://luarocks.org/lua-cmsgpack-scm-1.rockspec
https://luarocks.org/lua-cmsgpack-0.4.0-0.rockspec
https://luarocks.org/lua-cmsgpack-0.3-1rockspec
https://luarocks.org/lua-cmsgpack-0.3.0-0.rockspec

Source is specified with git:// but this is no longer supported by Githib and needs to be changed to https:// instead.

below is an example of the needed update 

Before:
url = "git://github.com/antirez/lua-cmsgpack.git"

After:
url = "https://github.com/antirez/lua-cmsgpack.git"

**Comment by hishamhm** [comment]
@EncryptShawn Please upgrade to a recent version of LuaRocks, the CLI tool does the autoconversion and these URLs continue to work fine. The rockspecs themselves are not maintained by the website maintainers, but by the account owners.
