### ISSUE TITLE
lsqlite3 rock is outdated

### ISSUE THREAD

**Issue by FractalU** [luarocks/luarocks-site#201]
@dcurrie The current lsqlite3 0.9.5 rock is outdated. lsqlite3 0.9.6 is available.

Source URL: http://lua.sqlite.org/index.cgi/zip/lsqlite3_fsl09z.zip?uuid=fsl_9z

Note: There is also `lsqlite3_v096.zip` under http://lua.sqlite.org/index.cgi/zip/lsqlite3_v096.zip?uuid=v0.9.6 which contains the exact same content as `lsqlite3_fsl09z.zip`. `lsqlite3_v096.zip` is apparently a new thing. Previously, the name of the zip file always contained a letter at the end such as `lsqlite3_fsl09x.zip`, `lsqlite3_fsl09y.zip` or `lsqlite3_fsl09z.zip`.

**Comment by FractalU** [comment]
Actually, only the `uuid` parameter of the source URL specifies the version. The name of the zip file can be anything. It won't have an influence on the version. E.g. The URL http://lua.sqlite.org/index.cgi/zip/lsqlite3_v096.zip?uuid=v0.9.6 points to the same version as http://lua.sqlite.org/index.cgi/zip/I_love_unicorns.zip?uuid=v0.9.6.

**Comment by hishamhm** [comment]
@FractalU this issue tracker is for the codebase of the luarocks.org website, not for discussing individual rocks. Please contact rock maintainers directly! Thanks!

**Comment by FractalU** [comment]
@hishamhm Would be really nice if I could contact rock maintainers directly. I just don't see a way to do it. I already searched for other ways. I'm aware that this repo is not the supposed place to notify rock maintainers, but given the circumstances, I don't see any better way. This way is still much better than no communication at all. If you have a better solution, I'm open.

Given that, it seems that the `lsqlite3` rock maintainer @dcurrie went radio silent while there is a new version of `lsqlite3` available. So, the `lsqlite3` rock remains outdated and apparently nobody except me seems to care about it.

Is there a way to deal with inactive rock maintainers? Packages should eventually be updated. Of course there is already an issue https://github.com/luarocks/luarocks-site/issues/199.

**Comment by FractalU** [comment]
@dcurrie Thanks for the update. Haven't expected it.
