### ISSUE TITLE
Add uploader permissions

### ISSUE THREAD

**Issue by technomancy** [luarocks/luarocks-site#204]
I have a library that I'm not that interested in maintaining the luarock for, but another maintainer is. I'd like to grant them access to upload new versions. I can't find any documentation about how to do this.

I would be OK transferring ownership altogether if that's necessary, but I can't find any documentation for that either. All I see is some notes about claiming ownership of a github project, but this library is not developed on github.

Is there a way to do this?

**Comment by technomancy** [comment]
Thanks for the clarification. I'll see about getting a new user created, and maybe updating the wiki.

**Comment by technomancy** [comment]
Thanks. Sorry for the delay. I finally got around to registering a new user.

Could you transfer https://luarocks.org/modules/technomancy/fennel over to this user: https://luarocks.org/modules/fennel

**Comment by hishamhm** [comment]
@technomancy Done!!

**Comment by technomancy** [comment]
Perfect; thank you.
