### ISSUE TITLE
ownership change request: kong-plugin-ddtrace

### ISSUE THREAD

**Issue by cgilmour** [luarocks/luarocks-site#205]
Hi! I would like to "transfer" the ownership of [kong-plugin-ddtrace](https://luarocks.org/modules/cgilmour/kong-plugin-ddtrace) from myself to a colleague, @dmehala.

From other issues ([here](https://github.com/luarocks/luarocks-site/issues/204#issuecomment-1963216915) and [here](https://github.com/luarocks/luarocks-site/issues/133#issuecomment-393265521)), it seems that the process is for the module to be mirrored first under the new username, and then a luarocks maintainer updates the root manifest so the module name uses the replacement.
Is that correct?

Thanks!
Caleb

**Comment by hishamhm** [comment]
Yes, that's the correct process. Done!
