### ISSUE TITLE
Proposal: rewrite luarocks-site with more widely adopted web technologies and explore UI/UX improvements

### ISSUE THREAD

**Issue by NTBBloodbath** [luarocks/luarocks-site#208]
Hi there, I know this can feel a bit off especially due to all the time spent doing this, but I would like to propose rewriting the luarocks site using more widely adopted web technologies instead of the MoonScript lapis framework.

### Benefits of rewriting the site

- Increased incentive for others to contribute: By using more popular technologies, the project may become more approachable to a wider range of developers, potentially increasing the number of people who are willing to contribute to the site.
- Easier maintenance: Widely adopted web technologies often have larger communities and more resources available, which can make it easier to find help and maintain the codebase.
- Enhanced user experience: A more modern look and feel can provide a more intuitive and user-friendly experience for visitors. Consider using a CSS framework like [TailwindCSS](https://tailwindcss.com/) to streamline styling and allow for better responsiveness on different screen sizes, especially in sections like the homepage in mobile view.

<details>
	<summary>Mobile homepage view demo</summary>

![Homepage in mobile](https://github.com/luarocks/luarocks-site/assets/36456999/312aa195-9fe6-467f-9c6b-2bbdbb38753d).

</details>

<details>
	<summary>npm.js mobile view demo for comparison</summary>

![NPM package mobile view](https://github.com/luarocks/luarocks-site/assets/36456999/42db9dc6-85a1-4a76-9776-27f1c944f601)
> `npmjs.com` random package view page

---

![LuaRocks package mobile view](https://github.com/luarocks/luarocks-site/assets/36456999/49a7620c-0d5c-4288-9702-8b02bae21af3)
> `luarocks.org` random package view page

</details>

---

### Some additional features that I would like to add later

- Filtering: allow users to filter the list of LuaRocks packages by various criteria, such as name, category, or maintainer.
- Changelog adoption from rockspecs:
	- Leverage a `CHANGELOG.md` file from the repositories similar to the `LICENSE` file.
    	> This can be discussed further in the main luarocks repository if the idea is acceptable, as this is something that isn't implemented yet from that side either :).

---

I believe that these changes would make the `luarocks.org` site more user-friendly, easier to maintain, and more discoverable. I would love to hear your thoughts on this proposal and explore the possibilities together. Also please note that this is just a suggestion, and I'm open to other ideas :p

**Comment by Dich0tomy** [comment]
Does the lapis framework allow for mixing with other technologies? I assume you want to rewrite it incrementally, but lapis would have to support that, otherwise you'd be in a constant loop of catching up to the existing implementation *and* new one.

**Comment by leafo** [comment]
All of the things you want can be implemented in the current codebase. It seems like your proposition is that someone does a lot of upfront work on the off-chance that someone else can then do additional work to add these feature requests? Or are you offering that you would do these things if the technology wasn't so unfamiliar to you?

In any case, I may be biased, but I think rewriting is not a good idea. The existing codebase is relatively well organized and straight forward, if you wont to contribute I suggest taking a look at working with what's there.

**Comment by NTBBloodbath** [comment]
I would be willing to work on it during the free time I currently have, although you make a very reasonable point about doing a rewrite so perhaps the gain won't be as noticeable in the long term. For the same reason that I haven't seen the codebase much due to my ignorance about MoonScript, could you instruct me a little about it? Here are some points that interest me the most (I might be missing something, it's a bit late here):

- How exactly does the site structure work?
- Is the dependency on SassC only the CLI or also the library part? Since I read that it was deprecated and it would be good to migrate.
- Where is CoffeeScript used? I saw that it is a dependency, but I also don't know the language and where it is used, in case I need to use it too for making the changes.
- Why is Tup used and not something more standardized like GNU Make? I have no problem using Tup, but I'm curious about it :).
- In the case of Discount (or any other `markdown` executable as mentioned in the README), where is it used? Do I also need it to run the site?
- If a change requires interaction with databases (such as the filtering features), what would be the best way to perform and test it? Since I see that you use GCP for data storage.

---

Side question: no problem experimenting with TailwindCSS integration? I think that would reduce dependencies by removing Sass and also reducing overhead maintenance a bit. Since it is configurable I can retain exactly the same color palette if desired without changes, in case that's a concern. 

---

Without anything else for now, grateful for the response and apologies if I asked anything that may seem obvious, I'm not familiar with using Lua/MoonScript for web development _yet_ 😅. Thanks in advance for the guidance!

**Comment by leafo** [comment]
@NTBBloodbath I think before I invest a bunch of time explaining things, I think it might be worth it for you to try setting up the development environment via the instructions on the README. Also note that we have dockerfiles for testing/development in the repo if you want to go that direction. The site has only been tested to run on Linux. If you get stuck you can ask questions.

You can also join the MoonScript discord and ask questions there, there are a few people who have experience with Lapis (including myself) that can help point you in the right direction. https://discord.com/invite/Y75ZXrD

**Comment by NTBBloodbath** [comment]
Hi, thank you for the partial help provided, unfortunately I have decided not to contribute to the luarocks site and back off my plans. I hope someone is willing to use the awkward technologies that are currently in use and implement some of my ideas in the future in order to improve the site.

Cheers
